[package]
name = "snark-setup-operator"
version = "0.1.0"
authors = ["Kobi Gurkan <kobigurk@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10"
anyhow = "1"
tokio = { version = "0.2", features = [ "full" ] }
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
chrono = {version = "0.4", features = [ "serde" ] }
gumdrop = { version = "0.7" }
url = { version = "2" }
thiserror = { version = "1" }
warp = { version = "0.2" }
prometheus = { version = "0.10", features = ["process"] }
lazy_static = "1.4"
futures = { version = "0.3", default-features = false }
rand = "0.7"
tracing = "0.1"
tracing-subscriber = "0.2"
